### Site info:
title: 激安・格安・特価情報ツウ！
tagline: さまざまな特価や激安・格安なネット通販の情報をブログで掲載中！
author: 激安・格安・特価情報ツウ！
email: tokka@ipon.biz
description: "さまざまな特価や激安・格安なネット通販の情報をブログで掲載中！PC・PC周辺機器・デジカメ・家電を主にAmazon、NTT-X、楽天などで" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jekyll, theme, Freshman21"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tokka.github.io" # the base hostname & protocol for your site


### Personal info and site tools info:
twitter_username: tokka2
github_username:  tokka2
disqus_shortname: 
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Lijia Yu. I made the Freshman21 theme. Please enjoy it. # these are shown on aboutme-sidebar.
aboutme_photo: "/images/tokka2.gif" # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "ja" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    ja:
      Aboutme: "About Me"
      Archives: "アーカイブ"
      Blogroll: "ブログロール"
      Categories: "カテゴリー"
      Copyright_Notice: "著作権表示"
      Recent_Posts: "新着記事"
      Tags: "タグ" 
      Previous: "前へ"
      Next: "次へ"
      PostedInCategories: "カテゴリー:"
      Taggedwith: "| タグ:"
      PostDate: "| 更新日時: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Freshman21
      href: http://yulijia.net/freshman21
      title: Another Jekyll blog theme
    - name: author's website
      href: http://yulijia.net/
      title: Lijia Yu's website


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5


# SCSS

sass:
  style: :compressed
